# Generated by Django 2.1.3 on 2018-11-24 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('place_name', models.CharField(blank=True, max_length=50, null=True)),
                ('admin_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'pincode',
            },
        ),
        migrations.CreateModel(
            name='PolygonMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('co_ordinates', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'polygonmapping',
            },
        ),
    ]
