# Generated by Django 2.1.3 on 2018-11-24 19:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonmapping',
            name='co_ordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
