# Generated by Django 2.1.3 on 2018-11-24 19:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pincode', '0003_auto_20181124_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplePolygonMapping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('co_ordinates', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'multiplepolygonmapping',
            },
        ),
    ]
